#!/usr/bin/env bash
# AIR Prompt 14 R2 targeted adaptive qualification.
# Reuses the already-valid Prompt-14 R1 correctness/transition/steady-state archive,
# fixes the R1 harness bug by running manifest-planned benchmarks with backend=auto,
# and packages all new adaptive evidence plus the original archive.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$HOME/Downloads/AIR-Performance14-R2-$STAMP"
TMP="$HOME/Downloads/AIR-Performance14-R2-base-$STAMP"
MODEL="${AIR_MODEL:-$HOME/Models/AIR/qwen2.5-0.5b-instruct-q4_k_m.gguf}"
RUN_NSYS="${AIR_RUN_NSYS:-1}"
JOBS="${JOBS:-2}"
mkdir -p "$OUT"/{adaptive,stale,nsys,source} "$TMP"
FAILURES=()
fail(){ FAILURES+=("$*"); printf 'FAIL: %s\n' "$*" >&2; }
finish(){
  if [ ${#FAILURES[@]} -gt 0 ]; then printf '%s\n' "${FAILURES[@]}" >"$OUT/FAILURE.txt"; fi
  rm -f "$HOME/Downloads/AIR-Performance14-R2-$STAMP.zip"
  (cd "$HOME/Downloads" && zip -qr "AIR-Performance14-R2-$STAMP.zip" "AIR-Performance14-R2-$STAMP")
  echo
  echo "=== PROMPT 14 R2 ARCHIVE ==="
  echo "$HOME/Downloads/AIR-Performance14-R2-$STAMP.zip"
  [ ${#FAILURES[@]} -eq 0 ]
}
trap finish EXIT

# Resolve the original Prompt-14 R1 archive unless explicitly supplied.
BASE_ARCHIVE="${AIR_P14_BASE_ARCHIVE:-}"
if [ -z "$BASE_ARCHIVE" ]; then
  BASE_ARCHIVE="$(find "$HOME/Downloads" -maxdepth 1 -type f -name 'AIR-Performance14-20*.zip' ! -name 'AIR-Performance14-R2-*' -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -1 | cut -d' ' -f2-)"
fi
if [ -z "$BASE_ARCHIVE" ] || [ ! -f "$BASE_ARCHIVE" ]; then
  fail "base Prompt-14 archive not found; set AIR_P14_BASE_ARCHIVE=/path/to/AIR-Performance14-<timestamp>.zip"
  exit 1
fi
cp "$BASE_ARCHIVE" "$OUT/base-evidence.zip"
unzip -q "$BASE_ARCHIVE" -d "$TMP" || { fail 'unable to extract base archive'; exit 1; }
BASE_ROOT="$(dirname "$(find "$TMP" -type f -name final-manifest.json -print -quit)")"
if [ ! -f "$BASE_ROOT/final-manifest.json" ]; then fail 'base archive has no final-manifest.json'; exit 1; fi
cp "$BASE_ROOT/final-manifest.json" "$OUT/final-manifest.json"
[ -f "$BASE_ROOT/strategy-summary.json" ] && cp "$BASE_ROOT/strategy-summary.json" "$OUT/strategy-summary.json"
[ -f "$BASE_ROOT/strategy-summary.md" ] && cp "$BASE_ROOT/strategy-summary.md" "$OUT/strategy-summary.md"
cp "$BASE_ROOT/prompts/p1042.txt" "$OUT/p1042.txt"
cp "$BASE_ROOT/prompts/p54.txt" "$OUT/p54.txt"

BUILD="$ROOT/build-performance14"
BENCH="$BUILD/air-bench"; CLI="$BUILD/air-cli"; PROBE="$BUILD/air-strategy-probe"
need_build=0
for x in "$BENCH" "$CLI" "$PROBE"; do [ -x "$x" ] || need_build=1; done
if [ "$need_build" -eq 0 ]; then
  ver="$($BENCH --version 2>/dev/null || true)"
  [[ "$ver" == *"0.9.11"* ]] || need_build=1
fi
if [ "$need_build" -eq 1 ]; then
  cmake -S "$ROOT" -B "$BUILD" -DCMAKE_BUILD_TYPE=Release -DAIR_ENABLE_CUDA=ON -DAIR_BUILD_RESEARCH=ON >"$OUT/build-release.txt" 2>&1 || { fail 'R2 configure failed'; exit 1; }
  cmake --build "$BUILD" -j"$JOBS" >>"$OUT/build-release.txt" 2>&1 || { fail 'R2 build failed'; exit 1; }
else
  echo 'reused existing AIR 0.9.11 build-performance14 binaries' >"$OUT/build-release.txt"
fi
ctest --test-dir "$BUILD" --output-on-failure --timeout 180 >"$OUT/ctest-release.txt" 2>&1 || fail 'R2 complete ctest failed'

{
  echo harness=AIR-Performance14-R2-adaptive
  echo date="$(date -Is)"
  echo base_archive="$BASE_ARCHIVE"
  "$BENCH" --version
  "$CLI" cuda-info
  nvidia-smi
} >"$OUT/preflight.txt" 2>&1
sha256sum "$MODEL" >"$OUT/model-sha256.txt"
"$CLI" fingerprint "$MODEL" >"$OUT/fingerprint.json" 2>"$OUT/fingerprint.stderr" || fail 'R2 fingerprint failed'

# Current identity must exactly match the final manifest generated by R1.
python3 - "$OUT/fingerprint.json" "$OUT/final-manifest.json" <<'PY' || { fail 'current model/hardware fingerprint does not match final manifest'; exit 1; }
import json,sys
fp=json.load(open(sys.argv[1])); mf=json.load(open(sys.argv[2]))
assert fp['air_version']=='0.9.11'
assert mf['schema_version']==10 and mf['air_version']=='0.9.11'
assert fp['model_digest']==mf['model_digest'], (fp['model_digest'],mf['model_digest'])
assert fp['hardware_digest']==mf['hardware_digest'], (fp['hardware_digest'],mf['hardware_digest'])
assert all(s['decode_output_quantized_linear']=='batch-reuse8' for s in mf['strategies'])
PY

# Persist reproducible source hashes for the exact installed source used by this R2 run.
find "$ROOT/include" "$ROOT/src" "$ROOT/tests" "$ROOT/scripts" "$ROOT/research" -type f -print0 2>/dev/null \
  | sort -z | xargs -0 sha256sum >"$OUT/source-sha256.txt"
sha256sum "$ROOT/CMakeLists.txt" "$ROOT/README.md" "$ROOT/ROADMAP.md" >>"$OUT/source-sha256.txt"
cp "$ROOT/scripts/validate-performance14-adaptive-r2-machine.sh" "$OUT/source/"
cp "$ROOT/scripts/validate-performance14-machine.sh" "$OUT/source/"

# Stale identity rejection: required manifests must fail closed.
python3 - "$OUT/final-manifest.json" "$OUT/stale/model.json" "$OUT/stale/hardware.json" <<'PY'
import json,sys
base=json.load(open(sys.argv[1]))
a=json.loads(json.dumps(base)); a['model_digest']='fnv1a64:0000000000000000'; json.dump(a,open(sys.argv[2],'w'),indent=2)
b=json.loads(json.dumps(base)); b['hardware_digest']='fnv1a64:0000000000000000'; json.dump(b,open(sys.argv[3],'w'),indent=2)
PY
set +e
"$BENCH" -m "$MODEL" --backend auto --manifest "$OUT/stale/model.json" --require-manifest --prompt-file "$OUT/p54.txt" --tokens 1 --warmup 0 --runs 1 --concurrency 1 --output "$OUT/stale/model-bench.json" >"$OUT/stale/model.txt" 2>&1
model_rc=$?
"$BENCH" -m "$MODEL" --backend auto --manifest "$OUT/stale/hardware.json" --require-manifest --prompt-file "$OUT/p54.txt" --tokens 1 --warmup 0 --runs 1 --concurrency 1 --output "$OUT/stale/hardware-bench.json" >"$OUT/stale/hardware.txt" 2>&1
hardware_rc=$?
set -e
printf '%s\n' "$model_rc" >"$OUT/stale/model.exit"; printf '%s\n' "$hardware_rc" >"$OUT/stale/hardware.exit"
[ "$model_rc" -ne 0 ] || fail 'stale model fingerprint was incorrectly accepted'
[ "$hardware_rc" -ne 0 ] || fail 'stale hardware fingerprint was incorrectly accepted'

MF="$OUT/final-manifest.json"
# These were the four invalid R1 probes. Backend auto is required for Strategy Lab.
"$BENCH" -m "$MODEL" --backend auto --manifest "$MF" --require-manifest --prompt-file "$OUT/p1042.txt" \
  --tokens 4 --warmup 0 --runs 1 --concurrency 1 --strategy-objective minimum-vram --strategy-horizon-tokens 10000 \
  --output "$OUT/adaptive/minimum-vram.json" >"$OUT/adaptive/minimum-vram.txt" 2>&1 || fail 'R2 minimum-vram probe failed'
"$BENCH" -m "$MODEL" --backend auto --manifest "$MF" --require-manifest --prompt-file "$OUT/p1042.txt" \
  --tokens 4 --warmup 0 --runs 1 --concurrency 1 --strategy-objective maximum-throughput --strategy-horizon-tokens 10000 \
  --strategy-prepared-memory-budget-bytes 536870912 --output "$OUT/adaptive/limited-vram.json" >"$OUT/adaptive/limited-vram.txt" 2>&1 || fail 'R2 limited-vram probe failed'
"$BENCH" -m "$MODEL" --backend auto --manifest "$MF" --require-manifest --prompt-file "$OUT/p1042.txt" \
  --tokens 4 --warmup 0 --runs 1 --concurrency 1 --strategy-objective maximum-throughput --strategy-horizon-tokens 10000 \
  --output "$OUT/adaptive/cold-long.json" >"$OUT/adaptive/cold-long.txt" 2>&1 || fail 'R2 cold-long probe failed'
"$BENCH" -m "$MODEL" --backend auto --manifest "$MF" --require-manifest --prompt-file "$OUT/p54.txt" \
  --tokens 4 --warmup 0 --runs 1 --concurrency 1 --strategy-objective maximum-throughput \
  --output "$OUT/adaptive/short-cold.json" >"$OUT/adaptive/short-cold.txt" 2>&1 || fail 'R2 short-cold probe failed'

# Reconfirm hot-state hysteresis and final measured eviction without qualification override.
"$PROBE" -m "$MODEL" --manifest "$MF" --medium-prompt-file "$OUT/p1042.txt" --small-prompt-file "$OUT/p54.txt" \
  --scenario hot-dense --horizon-tokens 10000 --output "$OUT/adaptive/hot-dense.json" >"$OUT/adaptive/hot-dense.txt" 2>&1 || fail 'R2 hot-dense probe failed'
"$PROBE" -m "$MODEL" --manifest "$MF" --medium-prompt-file "$OUT/p1042.txt" --small-prompt-file "$OUT/p54.txt" \
  --scenario eviction --horizon-tokens 10000 --output "$OUT/adaptive/final-eviction.json" >"$OUT/adaptive/final-eviction.txt" 2>&1 || fail 'R2 final eviction probe failed'

python3 - "$OUT" <<'PY' || fail 'R2 adaptive Strategy Lab validation failed'
import json,sys,pathlib
p=pathlib.Path(sys.argv[1])
def j(n): return json.load(open(p/'adaptive'/n))
minv=j('minimum-vram.json'); budget=j('limited-vram.json'); cold=j('cold-long.json'); small=j('short-cold.json')
hot=j('hot-dense.json'); ev=j('final-eviction.json')
for d in (minv,budget,cold,small):
    assert d['planner_mode']=='adaptive', d['planner_mode']
    assert d['manifest_id'].endswith('-final'), d['manifest_id']
assert minv['runs'][0]['strategy_id']=='reuse8-p1042'
assert minv['decode_output_linear_tactic']=='batch-reuse8'
assert budget['runs'][0]['strategy_id']=='reuse8-p1042'
assert any(c['strategy_id']=='dense-p1042' and c['disposition']=='rejected:memory-infeasible' for c in budget['runs'][0]['strategy_candidates'])
assert cold['runs'][0]['strategy_id']=='dense-p1042' and cold['runs'][0]['plan_preparation_ms']>0
assert cold['decode_output_linear_tactic']=='batch-reuse8'
assert small['runs'][0]['strategy_id']=='reuse8-p54'
assert hot['first']['strategy_id']=='dense-p1042' and hot['second']['strategy_id']=='dense-p1042'
assert hot['second']['strategy_prepared_state_hot'] is True and hot['second']['plan_preparation_ms']<1.0
assert ev['qualification_allow_unknown_eviction'] is False
assert ev['first']['strategy_id']=='dense-p1042' and ev['second']['strategy_id']=='reuse8-p54'
assert ev['second']['plan_eviction_ms']>0
assert ev['snapshot']['planned_decode_output_linear_tactic']=='batch-reuse8'
PY

# Optional Nsight proof of the adaptive product path. This is supplemental, not a new optimization study.
NSYS="$(command -v nsys 2>/dev/null || true)"
if [ "$RUN_NSYS" = 1 ] && [ -n "$NSYS" ]; then
  PROFILE_BUILD="$ROOT/build-performance14-profile"
  cmake -S "$ROOT" -B "$PROFILE_BUILD" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DAIR_ENABLE_CUDA=ON -DAIR_ENABLE_NVTX=ON -DAIR_BUILD_RESEARCH=ON >"$OUT/nsys/build-profile.txt" 2>&1
  if [ $? -eq 0 ]; then cmake --build "$PROFILE_BUILD" -j"$JOBS" >>"$OUT/nsys/build-profile.txt" 2>&1; fi
  PB="$PROFILE_BUILD/air-bench"
  if [ -x "$PB" ]; then
    prefix="$OUT/nsys/adaptive-dense-p1042"
    "$NSYS" profile --trace=cuda,nvtx,osrt --sample=none --force-overwrite=true -o "$prefix" \
      "$PB" -m "$MODEL" --backend auto --manifest "$MF" --require-manifest --prompt-file "$OUT/p1042.txt" \
      --tokens 4 --warmup 0 --runs 1 --concurrency 1 --strategy-objective maximum-throughput --strategy-horizon-tokens 10000 \
      --output "$prefix-bench.json" >"$prefix-profile.txt" 2>&1 || true
    [ -f "$prefix.nsys-rep" ] && "$NSYS" stats --report nvtx_sum --report cuda_gpu_kern_sum --report cuda_gpu_mem_time_sum --report cuda_gpu_mem_size_sum --report cuda_api_sum "$prefix.nsys-rep" >"$prefix-stats.txt" 2>&1 || true
  fi
else
  echo 'Nsight Systems unavailable or disabled' >"$OUT/nsys/SKIPPED.txt"
fi

if [ ${#FAILURES[@]} -eq 0 ]; then echo PASS >"$OUT/R2-PASS.txt"; fi
